wiki/encyclopedia/urls.py
from django.urls import path

from . import views



app_name = "encyclopedia"
urlpatterns = [
    
    path("", views.index, name="index"),
    path("query", views.query, name="query"),
    path("random", views.random, name="random"),
    path("newpage", views.newpage, name="newpage"),
    path("editpage-<str:entry>", views.editpage, name="editpage"),
    path("<str:title>", views.search, name="search"),

]

wiki/wiki/urls.py
from django.contrib import admin
from django.urls import include, path

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include("encyclopedia.urls"))
]

wiki/encyclopedia/models.py
from django.db import models

# Create your models here.

wiki/encyclopedia/views.py
from django.shortcuts import render, redirect
from django.http import HttpResponse , HttpResponseRedirect
import markdown2
from django import forms
from . import util
import re
from django.urls import reverse
from random import choice




def index(request):
    return render(request, "encyclopedia/index.html", {
        "entries": util.list_entries()
    })


def search(request, title):
    
    response = util.get_entry(title)

    if response is None:

        return render(request, "encyclopedia/error.html", {
            "message" : "requested page was not found", 
        })

    
    return render(request, "encyclopedia/response.html", {
       "response" : markdown2.markdown(response),
       "title" : title
   })


def query(request):

    if request.method == "POST":

        entry = request.POST['q'].lower()

        response = util.get_entry(entry)


        if response is None:

            entries = util.list_entries()

            possible_matches = []

            for i in entries:
            
                if entry in i.lower():

                    possible_matches.append(i)

            if len(possible_matches) == 0:

                return render(request, "encyclopedia/matches.html", {
                    "no_matches" : "no results"

                })

            return render(request,  "encyclopedia/matches.html", {
                "matches" : possible_matches,
            })
            
        
        return render(request, "encyclopedia/response.html", {
       "response" : markdown2.markdown(response),
       "title" : entry
        })



def newpage(request):

    if request.method == "POST":

        new_page = request.POST

        title = new_page["newpage_title"]

        content= new_page['newpage_content']

        entries = util.list_entries()

        for entry in entries:

            if entry.lower() == title.lower():

                return render(request, "encyclopedia/error.html", {

                    "message": "title already exists"
                })

        util.save_entry(title,content)

        return HttpResponseRedirect(reverse("encyclopedia:search", kwargs={"title" : title}))
        
    return render(request, "encyclopedia/newpage.html")


def editpage(request, entry):

    if request.method == "POST":

        new_content = request.POST['edited_content']

        util.save_entry(entry, new_content)

        return HttpResponseRedirect(reverse("encyclopedia:search", kwargs={"title" : entry}))

    markdown = util.get_entry(entry)

    return render(request, "encyclopedia/editpage.html" ,{

        "title": entry,
        "content" : markdown,

    })


def random(request):

    entries = util.list_entries()

    random = choice(entries)

    content = util.get_entry(random)

    return render(request, "encyclopedia/response.html" , {

        "title": random,
        "response": markdown2.markdown(content),
    })

wiki/encyclopedia/templates/encyclopedia/editpage.html
{% extends "encyclopedia/layout.html" %}

{% block title %}
 Edit 
{% endblock %}

{% block body %}

<center> 
    <form action="{% url 'encyclopedia:editpage' entry=title %}" method= "post"> 
        {% csrf_token %}
        <div>
            <h1 style="text-transform:capitalize">{{title}}</h1>
        </div>

        <div> 
            <h6>Markdown Content</h6>

            <textarea name="edited_content" id="textarea" cols="30" rows="10">{{content}}</textarea>

        </div>

        <button>Edit</button>

    </form>

</center>
{% endblock %}

wiki/encyclopedia/templates/encyclopedia/error.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>error</title>
</head>
<body>

    {{message}}
    
</body>
</html>

wiki/encyclopedia/templates/encyclopedia/index.html
{% extends "encyclopedia/layout.html" %}

{% block title %}
    Encyclopedia
{% endblock %}

{% block body %}
    <h1>All Pages</h1>

    <ul>
        {% for entry in entries %}
            <li> <a href="{% url 'encyclopedia:search' title=entry %}" style="text-transform:capitalize">{{entry}}</a></li>
        {% endfor %}
    </ul>

{% endblock %}

wiki/encyclopedia/templates/encyclopedia/layout.html
{% load static %}

<!DOCTYPE html>

<html lang="en">
    <head>
        <title>{% block title %}{% endblock %}</title>
        <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/css/bootstrap.min.css" integrity="sha384-Vkoo8x4CGsO3+Hhxv8T/Q5PaXtkKtu6ug5TOeNV6gBiFeWPGFN9MuhOf23Q9Ifjh" crossorigin="anonymous">
        <link href="{% static 'encyclopedia/styles.css' %}" rel="stylesheet">
    </head>
    <body>
        <div class="row">
            <div class="sidebar col-lg-2 col-md-3">
                <h2>Wiki</h2>
                <form action="{% url 'encyclopedia:query'%}" method="post">
                    {% csrf_token %}
                    <input class="search" type="text" name="q" placeholder="Search Encyclopedia">
                </form>
                <div>
                    <a href="{% url 'encyclopedia:index' %}">Home</a>
                </div>
                <div>
                    <a href="{% url 'encyclopedia:newpage' %}">Create New Page</a>
                </div>
                <div>
                    <a href="{% url 'encyclopedia:random' %}">Random Page</a>
                </div>
                {% block nav %}
                {% endblock %}
            </div>
            <div class="main col-lg-10 col-md-9">
                {% block body %}
                {% endblock %}
            </div>
        </div>

    </body>
</html>

wiki/encyclopedia/templates/encyclopedia/matches.html
{% extends "encyclopedia/layout.html" %}

{% block title %}

    matches

{% endblock %}

{% block body %}
    {% if no_matches %}

        {{no_matches}}

    {% endif %}

    <ul> 
        {% for match in matches %}
    
            <li><a href="{% url 'encyclopedia:search' title=match %}">{{match}}</a></li>
 
        {% endfor %}
    </ul>   
    
{% endblock %}

wiki/encyclopedia/templates/encyclopedia/newpage.html
{% extends "encyclopedia/layout.html" %}
    
    
{% block title %}
    newpage
{% endblock %}

{% block body %}


   <center> 

        <div class="container">

            <h6>Create New Page</h6>    

            <form action="{% url 'encyclopedia:newpage' %}" method="post"> 
                {% csrf_token %}
            
                <div style="margin-bottom:2%"> 
                    <input placeholder="title" name="newpage_title" type="text">
                </div>
        
                <div> 
                    <textarea name="newpage_content" placeholder="markdown content" id="textarea" ></textarea>
                </div>

                <div>
                    <button>Save</button>
                </div>

            </form>

        </div>

    </center>
    


{% endblock %}    

    

wiki/encyclopedia/templates/encyclopedia/response.html
{% extends "encyclopedia/layout.html" %}

{% block title %}
   {{title}}
{% endblock %}

{% block body %}

    {{response|safe}}

    <a href="{% url 'encyclopedia:editpage' entry=title %}">Edit</a>

{% endblock %}